<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>0.2.3</AssemblyVersion>
    <FileVersion>0.2.3</FileVersion>
    <Version>0.2.3</Version>
    <NeutralLanguage>en</NeutralLanguage>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <Nullable>enable</Nullable>
	<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	<ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Macros\For Each Loop.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\For Each Loop with Break.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\For Loop.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\For Loop with Break.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\For Loop with Break2 (break is unused).json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\While Loop.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\For Each Loop with Break2 (break is unused).json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\Is Valid.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\Reverse for Each Loop.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\Flip Flop.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\DoOnce MultiInput2 (reset is unused).json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\DoOnce MultiInput.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\Do Once2 (reset is unused).json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\Do Once.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\Do N.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\Foreach Enum.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\For Each Loop with Break4 (break is unused no loop body).json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Macros\For Each Loop with Break3 (no loop body).json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutomaticGraphLayout" Version="1.1.12" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="12.1.0" />
    <PackageReference Include="AvaloniaEdit.TextMate" Version="12.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\CUE4Parse\CUE4Parse\CUE4Parse.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <AvaloniaResource Include="Resources\*" />
  </ItemGroup>
	
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
	
  <ItemGroup>
    <Compile Update="Views\ProgressWindow.axaml.cs">
      <DependentUpon>ComparingProgressWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\CompareSettingsWindow.axaml.cs">
      <DependentUpon>CompareSettingsWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Controls\AddNodeMenu.axaml.cs">
      <DependentUpon>AddNodeMenu.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Controls\NodeContextMenu.axaml.cs">
      <DependentUpon>NodeContextMenu.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
